// Loads the synced dataset. The SOURCE OF TRUTH is the repo root file
// ../../data/internships.json. This local copy at src/data/internships.json is
// generated by `python ../scripts/sync_web_data.py` and must not be hand-edited.

import raw from "@/data/internships.json";
import type { Internship } from "./types";

export const internships: Internship[] = raw as Internship[];
