#!/usr/bin/env python3
"""Generate a data quality / status report from data/internships.json.

Standard-library only. Does NOT install or require any third-party package.
This is a LOCAL report only -- it never fetches web pages or current web state.

Output:
  - docs/status_report.md

Exit code:
    0  -> report generated
    1  -> data file missing / invalid JSON / write error
"""

import datetime
import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
DATA_PATH = os.path.join(PROJECT_ROOT, "data", "internships.json")
REPORT_PATH = os.path.join(PROJECT_ROOT, "docs", "status_report.md")

REVIEW_SOON_DAYS = 14

# Fields to tabulate as simple counts.
COUNT_FIELDS = [
    ("Status", "status"),
    ("Category", "category"),
    ("Location type", "location_type"),
    ("Source type", "source_type"),
    ("Requires U.S. citizenship", "requires_us_citizenship"),
    ("Freshman/sophomore friendly", "freshman_sophomore_friendly"),
    ("AI relevance", "ai_relevance"),
    ("Full-stack relevance", "full_stack_relevance"),
]


def comp_is_known(entry):
    note = (entry.get("compensation_note") or "").strip()
    return bool(note) and note.lower() != "unclear"


def load_data():
    with open(DATA_PATH, "r", encoding="utf-8-sig") as fh:
        return json.load(fh)


def parse_date(s):
    if not isinstance(s, str) or not re.match(r"^\d{4}-\d{2}-\d{2}$", s):
        return None
    try:
        return datetime.date(*[int(x) for x in s.split("-")])
    except ValueError:
        return None


def count_by(entries, field):
    counts = {}
    for e in entries:
        key = e.get(field)
        key = "(missing)" if key in (None, "") else str(key)
        counts[key] = counts.get(key, 0) + 1
    return counts


def render_counts(title, counts):
    lines = ["### %s" % title, ""]
    if not counts:
        lines.append("_None._")
        lines.append("")
        return lines
    for key in sorted(counts, key=lambda k: (-counts[k], k)):
        lines.append("- **%s**: %d" % (key, counts[key]))
    lines.append("")
    return lines


def is_unclear_text(value):
    """True when a free-text note conveys no definite information."""
    text = (value or "").strip().lower()
    if not text:
        return True
    return text == "unclear" or "not stated" in text or "not explicitly" in text \
        or text.startswith("unclear")


def main():
    if not os.path.exists(DATA_PATH):
        print("ERROR: data file not found: %s" % DATA_PATH, file=sys.stderr)
        return 1
    try:
        data = load_data()
    except ValueError as exc:
        print("ERROR: data file is not valid JSON: %s" % exc, file=sys.stderr)
        return 1
    if not isinstance(data, list):
        print("ERROR: top-level JSON must be an array.", file=sys.stderr)
        return 1

    today = datetime.date.today()
    total = len(data)

    # Date range.
    dated = [(e, parse_date(e.get("last_verified_date"))) for e in data]
    valid_dates = [d for _, d in dated if d]
    oldest = min(valid_dates).isoformat() if valid_dates else "N/A"
    newest = max(valid_dates).isoformat() if valid_dates else "N/A"

    # Unclear note counts.
    sponsorship_unclear = sum(1 for e in data if is_unclear_text(e.get("sponsorship_note")))
    workauth_unclear = sum(1 for e in data if is_unclear_text(e.get("work_authorization_note")))

    # Needs re-verification soon (> REVIEW_SOON_DAYS old, or undated).
    needs_review = []
    for e, d in dated:
        if d is None:
            needs_review.append((e, None))
        elif (today - d).days > REVIEW_SOON_DAYS:
            needs_review.append((e, (today - d).days))

    lines = []
    lines.append("# Data Status Report")
    lines.append("")
    lines.append("_Generated by `scripts/generate_status_report.py` from "
                 "`data/internships.json`. Local report only — no web state is fetched._")
    lines.append("")
    lines.append("**Report date:** %s" % today.isoformat())
    lines.append("**Total entries:** %d" % total)
    lines.append("")
    lines.append("**Last verified — oldest:** %s  " % oldest)
    lines.append("**Last verified — newest:** %s" % newest)
    lines.append("")

    lines.append("## Counts")
    lines.append("")
    for title, field in COUNT_FIELDS:
        lines += render_counts(title, count_by(data, field))

    lines.append("## Notes completeness")
    lines.append("")
    lines.append("- Entries with **sponsorship_note** unclear/empty: %d / %d"
                 % (sponsorship_unclear, total))
    lines.append("- Entries with **work_authorization_note** unclear/empty: %d / %d"
                 % (workauth_unclear, total))
    lines.append("")

    # Compensation.
    known = [e for e in data if comp_is_known(e)]
    unclear = [e for e in data if not comp_is_known(e)]
    missing_ev = [e for e in data
                  if not (e.get("compensation_evidence") or "").strip()]
    lines.append("## Compensation")
    lines.append("")
    lines.append("- Entries with **known** compensation: %d / %d" % (len(known), total))
    lines.append("- Entries with **unclear** compensation: %d / %d" % (len(unclear), total))
    lines.append("")
    lines += render_counts("By compensation period", count_by(data, "compensation_period"))
    lines.append("### Roles with known compensation")
    lines.append("")
    if known:
        for e in sorted(known, key=lambda x: x.get("company", "").lower()):
            lines.append("- **%s** — %s — %s"
                         % (e.get("company", "?"), e.get("role", "?"),
                            e.get("compensation_note", "?")))
    else:
        lines.append("- None.")
    lines.append("")
    lines.append("### Roles with missing/empty compensation evidence")
    lines.append("")
    if missing_ev:
        for e in missing_ev:
            lines.append("- **%s** — %s" % (e.get("company", "?"), e.get("role", "?")))
    else:
        lines.append("- None. Every entry has a compensation evidence note.")
    lines.append("")
    lines.append("_Averages are intentionally not computed (pay periods and ranges "
                 "differ; values are shown as listed on official pages only)._")
    lines.append("")

    lines.append("## Needs re-verification soon")
    lines.append("")
    lines.append("_Rule: `last_verified_date` older than %d days relative to the "
                 "report date (%s), or missing. This is a local freshness heuristic "
                 "and does not reflect the live posting._"
                 % (REVIEW_SOON_DAYS, today.isoformat()))
    lines.append("")
    if not needs_review:
        lines.append("- None. All entries were verified within the last %d days."
                     % REVIEW_SOON_DAYS)
    else:
        for e, age in needs_review:
            if age is None:
                detail = "missing/invalid last_verified_date"
            else:
                detail = "%d days old (last verified %s)" % (age, e.get("last_verified_date"))
            lines.append("- **%s** — %s — %s"
                         % (e.get("company", "?"), e.get("role", "?"), detail))
    lines.append("")

    with open(REPORT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    print("Generated docs/status_report.md")
    print("Total entries: %d | oldest: %s | newest: %s" % (total, oldest, newest))
    print("Needs re-verification soon: %d" % len(needs_review))
    return 0


if __name__ == "__main__":
    sys.exit(main())
