#!/usr/bin/env python3
"""Generate a Markdown internships table from data/internships.json.

Standard-library only. Does NOT install or require any third-party package.

Outputs:
  - docs/internships_table.md         (standalone table document)
  - README.md                          (content between the table markers only)

README markers (added if missing, content between them replaced otherwise):
    <!-- INTERNSHIPS_TABLE_START -->
    <!-- INTERNSHIPS_TABLE_END -->

Sorting: status (Open, then Unclear, then Closed), then last_verified_date
descending, then company ascending.

Exit code:
    0  -> generated successfully
    1  -> data file missing / invalid JSON / write error
"""

import datetime
import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
DATA_PATH = os.path.join(PROJECT_ROOT, "data", "internships.json")
README_PATH = os.path.join(PROJECT_ROOT, "README.md")
TABLE_DOC_PATH = os.path.join(PROJECT_ROOT, "docs", "internships_table.md")

START_MARKER = "<!-- INTERNSHIPS_TABLE_START -->"
END_MARKER = "<!-- INTERNSHIPS_TABLE_END -->"

STATUS_ORDER = {"Open": 0, "Unclear": 1, "Closed": 2}

COLUMNS = [
    "Company", "Role", "Location", "Type", "Category", "Pay", "AI", "Full-Stack",
    "Citizenship", "Status", "Last Verified", "Apply",
]


def load_data():
    with open(DATA_PATH, "r", encoding="utf-8-sig") as fh:
        return json.load(fh)


def parse_date(s):
    if not isinstance(s, str) or not re.match(r"^\d{4}-\d{2}-\d{2}$", s):
        return None
    try:
        return datetime.date(*[int(x) for x in s.split("-")])
    except ValueError:
        return None


def sort_key(entry):
    rank = STATUS_ORDER.get(entry.get("status"), 3)
    d = parse_date(entry.get("last_verified_date"))
    # Descending date: valid dates first (0) ordered by negative ordinal.
    date_key = (0, -d.toordinal()) if d else (1, 0)
    return (rank, date_key, str(entry.get("company", "")).lower())


def cell(value):
    """Escape a value for a Markdown table cell; blank -> em dash."""
    text = "" if value is None else str(value)
    text = text.replace("\r", " ").replace("\n", " ").replace("|", "\\|").strip()
    return text if text else "—"


def work_auth_short(entry):
    """Compact, deterministic label derived from work_authorization_note.

    Keeps long notes out of the table while still flagging restrictions.
    """
    note = (entry.get("work_authorization_note") or "").strip()
    low = note.lower()
    if not note or low in ("unclear",) or low.startswith("not ") or "not stated" in low \
            or "not explicitly" in low:
        return "Unclear"
    if re.search(r"citizen|itar|clearance|permanent resident|u\.s\. person|export.control", low):
        return "Restricted"
    if re.search(r"sponsor|support.{0,6}visa|visa.{0,6}support", low):
        return "Sponsor/Visa"
    return "See notes"


def pay_label(entry):
    """Compact pay label for the table: compensation_note, else 'Unclear'."""
    note = (entry.get("compensation_note") or "").strip()
    return note if note else "Unclear"


def apply_cell(entry):
    url = (entry.get("application_url") or "").strip()
    if not url:
        return "N/A"
    safe = url.replace(" ", "%20").replace("(", "%28").replace(")", "%29")
    return "[Apply](%s)" % safe


def row_for(entry):
    return [
        cell(entry.get("company")),
        cell(entry.get("role")),
        cell(entry.get("location")),
        cell(entry.get("location_type")),
        cell(entry.get("category")),
        cell(pay_label(entry)),
        cell(entry.get("ai_relevance")),
        cell(entry.get("full_stack_relevance")),
        cell(entry.get("requires_us_citizenship")),
        cell(entry.get("status")),
        cell(entry.get("last_verified_date")),
        apply_cell(entry),
    ]


def build_table(entries):
    lines = []
    lines.append("| " + " | ".join(COLUMNS) + " |")
    lines.append("|" + "|".join(["---"] * len(COLUMNS)) + "|")
    for e in entries:
        lines.append("| " + " | ".join(row_for(e)) + " |")
    return "\n".join(lines)


def build_readme_block(entries, today):
    count = len(entries)
    parts = [
        START_MARKER,
        "<!-- Generated by scripts/generate_readme_table.py. Do not edit by hand. -->",
        "",
        "**Verified postings:** %d &middot; **Last generated:** %s" % (count, today),
        "",
    ]
    if entries:
        parts.append(build_table(entries))
    else:
        parts.append("_No verified postings yet._")
    parts.append("")
    parts.append(END_MARKER)
    return "\n".join(parts)


def update_readme(block):
    if not os.path.exists(README_PATH):
        print("ERROR: README.md not found.", file=sys.stderr)
        return False
    with open(README_PATH, "r", encoding="utf-8-sig") as fh:
        text = fh.read()

    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if pattern.search(text):
        new_text = pattern.sub(lambda m: block, text)
    else:
        # Markers absent: append a new section at the end of the README.
        suffix = "" if text.endswith("\n") else "\n"
        new_text = text + suffix + "\n## Verified Internship Listings\n\n" + block + "\n"

    with open(README_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(new_text)
    return True


def write_table_doc(entries, today):
    count = len(entries)
    lines = [
        "# Verified Internship Listings",
        "",
        "_Generated by `scripts/generate_readme_table.py` from `data/internships.json`._",
        "_Do not edit by hand; re-run the script after the data changes._",
        "",
        "**Verified postings:** %d  " % count,
        "**Last generated:** %s" % today,
        "",
    ]
    if entries:
        lines.append(build_table(entries))
    else:
        lines.append("_No verified postings yet._")
    lines += [
        "",
        "### Column notes",
        "",
        "- **Type** = work arrangement (`location_type`).",
        "- **Pay** = `compensation_note` (official-page pay only; `Unclear` when not "
        "explicitly listed). Pay evidence is kept out of the table.",
        "- **AI** / **Full-Stack** = evidence-based relevance ratings.",
        "- **Citizenship** = `requires_us_citizenship` (Yes / No / Unclear).",
        "- Full evidence, work-authorization notes, and pay evidence live in "
        "`data/internships.json`, not in this table.",
        "",
        "> Postings change without notice. Always re-check the company's official "
        "application page before applying.",
        "",
    ]
    with open(TABLE_DOC_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))


def main():
    if not os.path.exists(DATA_PATH):
        print("ERROR: data file not found: %s" % DATA_PATH, file=sys.stderr)
        return 1
    try:
        data = load_data()
    except ValueError as exc:
        print("ERROR: data file is not valid JSON: %s" % exc, file=sys.stderr)
        return 1
    if not isinstance(data, list):
        print("ERROR: top-level JSON must be an array.", file=sys.stderr)
        return 1

    entries = sorted(data, key=sort_key)
    today = datetime.date.today().isoformat()

    write_table_doc(entries, today)
    block = build_readme_block(entries, today)
    if not update_readme(block):
        return 1

    print("Generated docs/internships_table.md (%d entr%s)."
          % (len(entries), "y" if len(entries) == 1 else "ies"))
    print("Updated README.md table section (between markers).")
    print("Last generated: %s" % today)
    return 0


if __name__ == "__main__":
    sys.exit(main())
